"""empty message

Revision ID: 7bb3700642ca
Revises: eced30c9b21e
Create Date: 2019-01-23 13:17:21.258078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bb3700642ca'
down_revision = 'eced30c9b21e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('account_balance', sa.Integer(), nullable=True))
    op.drop_column('user', 'account')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('account', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('user', 'account_balance')
    # ### end Alembic commands ###
