"""empty message

Revision ID: b61d07bc3656
Revises: 7bb3700642ca
Create Date: 2019-01-23 16:45:31.840027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b61d07bc3656'
down_revision = '7bb3700642ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_level', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_level', 'date_created')
    # ### end Alembic commands ###
