"""empty message

Revision ID: c4dc68b9e12e
Revises: 170364c7c400
Create Date: 2019-01-06 20:31:09.788606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4dc68b9e12e'
down_revision = '170364c7c400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pin', sa.String(length=128), nullable=True))
    op.drop_column('user', 'pip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('pip', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('user', 'pin')
    # ### end Alembic commands ###
