"""empty message

Revision ID: eced30c9b21e
Revises: c4dc68b9e12e
Create Date: 2019-01-06 22:03:20.737078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eced30c9b21e'
down_revision = 'c4dc68b9e12e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_pin_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_pin_confirmed')
    # ### end Alembic commands ###
